[package]
name = "openvpn-notifier"
version = "0.1.1"
authors = ["Thomas Morgan <tamorgan@outlook.com>"]

[dependencies]
pushover = "0.3.0"
pretty-bytes = "0.2.2"
chrono = "0.4.6"
time = "0.1.41"
clap = "2.32.0"